FROM python:3.8-slim

# WORKDIR /app

# COPY . /app

# RUN pip install --no-cache-dir -r requirements.txt

# CMD ["python", "main_script.py"]
WORKDIR /app
COPY hola_mundo.py .
CMD ["python","-u","hola_mundo.py"]